src/fints_downloader/urls.py
from django.urls import path

# from rest_framework.urlpatterns import format_suffix_patterns

from fints_downloader.views import (
    models,
    index,
    account,
    tag,
    importer,
    transaction,
    category,
    balance,
)


urlpatterns = [
    path("banklogins/", models.BankLoginList.as_view()),
    path("banklogins/<str:pk>/", models.BankLoginDetail.as_view()),
    path("transactions/", transaction.TransactionList.as_view(), name="transactions"),
    path(
        "transactions/categorize/",
        transaction.Categorize.as_view(),
        name="transactions_categorize",
    ),
    path(
        "transaction/<str:pk>/",
        transaction.TransactionDetail.as_view(),
        name="transaction",
    ),
    path("categories/", category.CategoryList.as_view(), name="categories"),
    path("category/<str:pk>/", category.CategoryDetail.as_view(), name="category"),
    path("", index.IndexView.as_view(), name="index"),
    path("balance/<str:pk>/", balance.BalanceLineChartJSON.as_view(), name="balance"),
    path("accounts/", account.AccountListView.as_view(), name="accounts"),
    path("account/<str:pk>", account.AccountView.as_view(), name="account"),
    path("tags/", tag.TagListView.as_view(), name="tags"),
    path("tag/<str:pk>", tag.TagView.as_view(), name="tag"),
    path(
        "import/accounts/",
        importer.ImportAccountsView.as_view(),
        name="import_accounts",
    ),
    path(
        "import/transactions/",
        importer.ImportTransactionsView.as_view(),
        name="import_transactions",
    ),
    path(
        "import/holdings/",
        importer.ImportHoldingsView.as_view(),
        name="import_holdings",
    ),
    path("import/tan/", importer.TANView.as_view(), name="import_tan"),
]

# urlpatterns = format_suffix_patterns(urlpatterns)

src/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("fints_downloader/", include("fints_downloader.urls")),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # path("", include("django.contrib.auth.urls")),
    path("", RedirectView.as_view(url="fints_downloader/", permanent=True)),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/fints_downloader/models/account.py
from django.db import models
from django.db.models import Q, Sum

# Used to generate URLs by reversing the URL patterns
from django.urls import reverse
from datetime import timedelta, datetime

from .basemodel import BaseModel
from .types import AccountTypes
from .transaction import Transaction


class Account(BaseModel):
    """Model representing an account"""

    bk_fields = ("number", "bic")
    bank_login = models.ForeignKey(
        "BankLogin",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        help_text="Login credentials used for this account",
    )
    iban = models.CharField(max_length=34, null=True, blank=True, help_text="IBAN")
    number = models.DecimalField(
        max_digits=30, decimal_places=0, help_text="Account number"
    )
    bic = models.CharField(
        max_length=11, null=True, blank=True, help_text="Bank identifier code"
    )
    type = models.CharField(
        max_length=2, choices=AccountTypes.choices, help_text="Type of account"
    )
    name = models.CharField(
        max_length=256, help_text="Account name", null=True, blank=True
    )
    init_balance = models.DecimalField(
        max_digits=32, decimal_places=2, default=0, help_text="Initial account balance"
    )

    def get_absolute_url(self):
        """Returns the url to access a detail record for this account."""
        return reverse("account", args=[str(self.id)])

    def get_current_balance(self):
        return self.sum_transactions()

    def sum_transactions(self, fromDate=None, toDate=None, add_filter=None):
        obj_filter = Q(src=self)
        if fromDate:
            obj_filter = obj_filter & Q(date__gte=fromDate)
        if toDate:
            obj_filter = obj_filter & Q(date__lte=toDate)
        if add_filter:
            obj_filter = obj_filter & add_filter
        sum = (
            Transaction.objects.filter(obj_filter).aggregate(sum=Sum("amount"))["sum"]
            or 0
        )
        return self.init_balance + sum

    def get_spending_cur_month(self):
        today = datetime.today()
        return self.sum_transactions(
            fromDate=today.replace(day=1), toDate=today, add_filter=Q(amount__lt=0)
        )

    def get_spending_last_month(self):
        last_month = datetime.today().replace(day=1) - timedelta(days=1)
        return self.sum_transactions(
            fromDate=last_month.replace(day=1),
            toDate=last_month,
            add_filter=Q(amount__lt=0),
        )

    def get_change_last_month(self):
        last_month = datetime.today().replace(day=1) - timedelta(days=1)
        return self.sum_transactions(
            fromDate=last_month.replace(day=1), toDate=last_month
        )

src/fints_downloader/models/banklogin.py
from django.db import models

# Used to generate URLs by reversing the URL patterns
from django.urls import reverse

from .basemodel import BaseModel


class BankLogin(BaseModel):
    """Model representing login credentials for a specific bank"""

    bk_fields = (
        "code",
        "user_id",
    )
    name = models.CharField(
        max_length=1024,
        null=True,
        blank=True,
        help_text="Decribing name of credentials",
    )
    user_id = models.CharField(max_length=1024, help_text="Login/user name")
    password = models.CharField(
        max_length=1024, help_text="Password or pin for this account"
    )
    tan_mechanism = models.CharField(
        max_length=3, null=True, blank=True, help_text="Default TAN mechanism"
    )
    bic = models.CharField(max_length=11, help_text="Bank identifier code")
    code = models.DecimalField(
        max_digits=8, decimal_places=0, help_text="German bank code"
    )
    server = models.CharField(
        max_length=1024, help_text="Bank fints server connection string"
    )
    enabled = models.BooleanField(default=True, help_text="Is this bank login enabled")
    tan_required = models.BooleanField(
        default=False, help_text="Last automatic access required a TAN"
    )

    def get_absolute_url(self):
        """Returns the url to access a detail record for these login
        credetinals."""
        return reverse("bank-login-detail", args=[str(self.id)])

src/fints_downloader/models/types.py
from django.db import models

# Used to generate URLs by reversing the URL patterns
from django.utils.translation import gettext_lazy as _


class CurrencyTypes(models.TextChoices):
    """Model representing different currencies."""

    EURO = "EUR", _("Euro")


class AccountTypes(models.TextChoices):
    """Model representing different account types."""

    CHECKING = "ch", _("checking")
    CREDIT_CARD = "cc", _("credit card")
    DEPOT = "dp", _("depot")
    FOREIGN = "fg", _("foreign")


class TagTypes(models.TextChoices):
    """Model representing different tag types."""

    CATEGORY = "ct", _("Category")
    OTHER = "ot", _("Other")

src/fints_downloader/forms.py
from django import forms
from django.forms import models
from django.forms.fields import MultipleChoiceField
from fints_downloader.models.account import Account
from fints_downloader.models.banklogin import BankLogin
from fints_downloader.models.transaction import Transaction
from fints_downloader.widgets import BootstrapDateTimePickerInput


class ImportAccountsForm(forms.Form):
    bank_login = forms.ModelChoiceField(
        queryset=BankLogin.objects.all(), help_text="Bank login"
    )
    # login_credentials_field = forms.ChoiceField(
    #   choices=[], help_text='TODO: help_text')

    # def __init__(self, *args, **kwargs):
    #    super(ImportForm, self).__init__(*args, **kwargs)
    #    self.fields['login_credentials_field'].choices = [
    #        (x.id, x.get_business_key()) for x in
    #           LoginCredentials.objects.all()]


class ImportAccountDetailsForm(forms.Form):
    account = forms.ModelChoiceField(
        queryset=Account.objects.filter(bank_login__isnull=False),
        help_text="Choose account as import source",
    )


class ImportHoldingsForm(ImportAccountDetailsForm):
    pass


class ImportTransactionsForm(ImportAccountDetailsForm):
    fromDate = forms.DateField(
        input_formats=["%d.%m.%Y"],
        widget=BootstrapDateTimePickerInput(),
        help_text="Beginndatum Transaktionszeitraum",
    )
    toDate = forms.DateField(
        input_formats=["%d.%m.%Y"],
        widget=BootstrapDateTimePickerInput(),
        help_text="Enddatum Transaktionszeitraum",
    )


class TANForm(forms.Form):
    tan = forms.CharField(max_length=16, help_text="TAN")


class CheckboxSelectMultipleAsTableIterator(models.ModelChoiceIterator):
    def choice(self, obj):
        return (self.field.prepare_value(obj), self.field.label_from_instance(obj), obj)


class CustomModelChoiceField(models.ModelMultipleChoiceField):
    def _get_choices(self):
        if hasattr(self, "_choices"):
            return self._choices
        return CheckboxSelectMultipleAsTableIterator(self)

    choices = property(_get_choices, MultipleChoiceField._set_choices)


class CategorizeForm(forms.Form):
    # categories are handled through FormView
    transactions = CustomModelChoiceField(
        queryset=Transaction.objects.filter(category__isnull=True).order_by("date"),
        widget=forms.CheckboxSelectMultiple,
    )

    def __init__(self, *args, **kwargs):
        self.category_text = None
        if args:
            self.category_text = args[0].get("category")
        super(CategorizeForm, self).__init__(*args, **kwargs)

    def is_valid(self):
        # run parent validation first
        valid = super(CategorizeForm, self).is_valid()

        # in case of error stop here
        if not valid:
            return valid

        if not self.category_text:
            self.add_error("category", "No category selected")
            return False

        return True

src/fints_downloader/views/account.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from fints_downloader.models.account import Account
from fints_downloader.models.types import AccountTypes


class AccountListView(LoginRequiredMixin, ListView):
    template_name = "accounts.html"
    model = Account
    context_object_name = "accounts"
    # paginate_by = 10

    def get_queryset(self):
        return super().get_queryset().exclude(type=AccountTypes.FOREIGN)


class AccountView(LoginRequiredMixin, DetailView):
    template_name = "account.html"
    model = Account

    # def get_context_data(self, *args, **kwargs):
    #    context = super(AccountView, self).get_context_data(*args, **kwargs)

    #    # context['num_banks'] = Bank.objects.count()

    #    return context

src/fints_downloader/views/balance.py
from chartjs.views.lines import BaseLineChartView
from django.db.models import Sum
from django.contrib.auth.mixins import LoginRequiredMixin

from fints_downloader.models.account import Account
from fints_downloader.models.transaction import Transaction


class BalanceLineChartJSON(LoginRequiredMixin, BaseLineChartView):
    def get_providers(seld):
        return ["Balance"]

    def get_labels(self):
        """Return 7 labels for the x-axis."""
        transactions = (
            Transaction.objects.filter(src__id=self.kwargs.get("pk"))
            .values("date")
            .annotate(Sum("amount"))
            .order_by("date")
        )
        labels = []
        for transaction in transactions:
            labels.append(transaction["date"])
        return labels
        # return ["January", "February", "March", "April", "May", "June", "July"]

    # def get_providers(self):
    #    """Return names of datasets."""
    #    return ["Central", "Eastside", "Westside"]

    def get_data(self):
        """Return 3 datasets to plot."""
        transactions = (
            Transaction.objects.filter(src__id=self.kwargs.get("pk"))
            .values("date")
            .annotate(Sum("amount"))
            .order_by("date")
        )
        init_balance = (
            Account.objects.filter(pk=self.kwargs.get("pk")).first().init_balance
        )
        # do something and convert to ...
        data = []
        last_amount = init_balance
        for transaction in transactions:
            last_amount += transaction["amount__sum"]
            data.append(last_amount)
        return [data]

src/fints_downloader/views/category.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from fints_downloader.models.category import Category


class CategoryList(LoginRequiredMixin, ListView):
    template_name = "categories.html"
    model = Category
    context_object_name = "categories"
    # paginate_by = 10

    # def get_queryset(self):
    #     return super().get_queryset().exclude(type=AccountTypes.FOREIGN)


class CategoryDetail(LoginRequiredMixin, DetailView):
    template_name = "category.html"
    model = Category

src/fints_downloader/views/index.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

# from fints_downloader.models import BankLogin, Account, Transaction, Holding


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "index.html"

    # def get_context_data(self, *args, **kwargs):
    #    context = super(IndexView, self).get_context_data(*args, *kwargs)

    #    context['num_logins'] = BankLogin.objects.count()
    #    context['accounts'] = {'count': Account.objects.count()}
    #    context['transactions'] = {'count': Transaction.objects.count()}
    #    context['holdings'] = {'count': Holding.objects.count()}

    #    return context

src/fints_downloader/views/tag.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from fints_downloader.models.tag import Tag


class TagListView(LoginRequiredMixin, ListView):
    template_name = "tags.html"
    model = Tag
    context_object_name = "tags"
    # paginate_by = 10

    # def get_queryset(self):
    #    return super().get_queryset().exclude(type=AccountTypes.FOREIGN)


class TagView(LoginRequiredMixin, DetailView):
    template_name = "tag.html"
    model = Tag

    # def get_context_data(self, *args, **kwargs):
    #    context = super(AccountView, self).get_context_data(*args, **kwargs)

    #    # context['num_banks'] = Bank.objects.count()

    #    return context

src/fints_downloader/views/transaction.py
from django.views.generic import ListView, DetailView, FormView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin

from fints_downloader.models.category import Category
from fints_downloader.models.transaction import Transaction
from fints_downloader.forms import CategorizeForm


class TransactionList(LoginRequiredMixin, ListView):
    template_name = "transactions.html"
    model = Transaction
    context_object_name = "transactions"
    # paginate_by = 10

    # def get_queryset(self):
    #    return super().get_queryset().exclude(type=AccountTypes.FOREIGN)


class TransactionDetail(LoginRequiredMixin, DetailView):
    template_name = "transaction.html"
    model = Transaction

    # def get_context_data(self, *args, **kwargs):
    #    context = super(AccountView, self).get_context_data(*args, **kwargs)

    #    # context['num_banks'] = Bank.objects.count()

    #    return context


class Categorize(LoginRequiredMixin, FormView):
    template_name = "categorize.html"
    form_class = CategorizeForm
    success_url = "/fints_downloader/transactions/categorize/"
    # context_object_name = 'accounts'
    # paginate_by = 10

    # def get_queryset(self):
    #    return super().get_queryset().exclude(type=AccountTypes.FOREIGN)

    def post(self, request, *args, **kwargs):
        form = CategorizeForm(request.POST)
        if form.is_valid():
            transactions = form.cleaned_data["transactions"]

            # check if category exists and create otherwise
            category = None
            try:
                category = Category.objects.get(name=form.category_text)
            except Category.DoesNotExist:
                category = Category.objects.create(name=form.category_text)

            for transaction in transactions:
                # Make sure we get the current version
                category.refresh_from_db()
                transaction.refresh_from_db()
                transaction.category = category
                transaction.save()
            return HttpResponseRedirect(self.success_url)

        context = {}
        if hasattr(context, "request"):
            context = request.context
        context["form"] = form
        return render(request, self.template_name, context)

    def get_context_data(self, *args, **kwargs):
        context = super(Categorize, self).get_context_data(*args, **kwargs)

        # transactions are handled through form
        # context['transactions'] = Transaction.objects.filter(
        #    category__isnull=True).order_by('date')
        context["categories"] = Category.objects.all()

        return context

src/fints_downloader/templates/__old.html
<ul class="sidebar-nav">
    <li><a href="">Home</a></li>
    <li><a href="">Import Transactions</a></li>
    <li><a href="">Import Balance</a></li>
    <li><a href="{% url 'import_holdings' %}">Import Holdings</a></li>
    <li><a href="{% url 'account_list' %}">All accounts</a></li>
  </ul>
  
  

src/fints_downloader/templates/account.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load humanize %}

{% block content %}
  <h1>{{account.name}}</h1>
  <div class="section">
    <!--Row with two equal columns-->
    <div class="row">
      <div class="col-md-3">
        <div class="card text-white bg-success mb-3">
          <div class="card-body">
            <h4 class="card-title">{% trans 'Current Balance' %}</h4>
            <h3 class="card-text">{{ account.get_current_balance|floatformat:2|intcomma }}</h3>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card text-white bg-danger mb-3">
          <div class="card-body">
            <h4 class="card-title">{% trans 'Spending cur. month' %}</h4>
            <h3 class="card-text">{{ account.get_spending_cur_month|floatformat:2|intcomma }}</h3>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card text-white bg-warning mb-3">
          <div class="card-body">
            <h4 class="card-title">{% trans 'Spending last month' %}</h4>
            <h3 class="card-text">{{ account.get_spending_last_month|floatformat:2|intcomma }}</h3>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card text-white bg-info mb-3">
          <div class="card-body">
            <h4 class="card-title">{% trans 'Change last month' %}</h4>
            <h3 class="card-text">{{ account.get_change_last_month|floatformat:2|intcomma }}</h3>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="box">
          <div class="box-header with-border">
            <h3 class="box-title">{% trans 'Account details' %}</h3>
          </div>
          <div class="box-body">
            <table class="table table-striped">
              <tr>
                <th>{% trans 'TEST1' %}</th>
              </tr>
              <tr>
                <td>TEST2</td>
              </tr>
            </table>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">{% trans 'Balance' %}</h3>
          </div>
          <div class="box-body">
            <canvas id="balanceChart" width="450" height="250"></canvas>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script type="text/javascript">
    $.get('{% url "balance" account.id %}', function(data) {
        var ctx = document.getElementById('balanceChart').getContext("2d");
        var balanceChart = new Chart(ctx, {
            type: 'line',
            data: data,
            options: {
                scales: {
                    xAxes: [{
                        ticks: {
                          source: 'auto'
                        }
                    }]
                }
            }
        });
    });
</script>
{% endblock %}

src/fints_downloader/templates/accounts.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Account list</h1>

<!-- TODO: -> enable/disable foreign accounts
           -> convert type to string -->
<!--data-classes="table-striped"-->
<table data-classes="table table-striped table-hover"
    data-toggle="table"
    data-pagination="true"
    data-search="true"
    data-show-pagination-switch="true"
    data-show-search-clear-button="true"
    data-show-toggle="true"
    data-sortable="true">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody>
{% for account in accounts %}
    <tr>
      <td><a href="{{ account.get_absolute_url }}">{{ account.name }}</a></td>
      <td>{{account.get_type_display}}</td>
      <td>{{account.get_current_balance}}</td>
    </tr>
{% endfor %}
  </tbody>
</table>

{% endblock %}

src/fints_downloader/templates/base_generic.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}
  <title>FinTS Downloader</title>
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% load static %}
  <!-- Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'js/popper-2.5.3.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-4.5.3.min.js' %}"></script>

  <!-- Boostrap table-->
  <link rel="stylesheet" href="{% static 'css/bootstrap-table-1.18.0.min.css' %}">
  <script src="{% static 'js/bootstrap-table-1.18.0.min.js' %}"></script>

  <!-- Font Awesome -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <!-- Moment.js -->
  <script src="{% static 'js/moment-with-locales.min.js' %}"></script>

  <!-- Tempus Dominus Bootstrap 4 -->
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css"
    integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
    integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

  <!-- ChartJS -->
  <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}" />
  <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>

  <!-- selectize.js -->
  <!-- we need the full version of jquery including ajax to properly work-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/selectize-0.13.0.bootstrap4.css' %}" />
  <script type="text/javascript" src="{% static 'js/selectize-0.13.0.standalone.js' %}"></script>

  <!-- Add additional CSS in static file -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
        <div class="nav-side-menu">
          <div class="menu-list">
            <a href="{% url 'index' %}" class="list-group-item list-group-item-action active">
              <i class="fa fa-home fa-lg"></i> {% trans 'Home' %} </a>

            {% if user.is_authenticated %}
            <div data-toggle="collapse" data-target="#imports" class="collapsed active">
              <a href="#" class="list-group-item list-group-item-action">
                <i class="fa fa-upload fa-lg"></i> {% trans 'Import' %} <span class="arrow"></span></a>
            </div>
            <div class="sub-menu collapse" id="imports">
              <a href="{% url 'import_transactions' %}" class="list-group-item list-group-item-action">
                <i class="fa fa-credit-card fa-lg"></i> {% trans 'Transactions' %} <span
                  class="badge badge-pill badge-primary pull-right">{{counts.transactions}}</span></a>
              <a href="{% url 'import_holdings' %}" class="list-group-item list-group-item-action">
                <i class="fa fa-money fa-lg"></i> {% trans 'Holdings' %} <span
                  class="badge badge-pill badge-primary pull-right">{{counts.holdings}}</span></a>
            </div>

            <a href="{% url 'accounts' %}" class="list-group-item list-group-item-action">
              <i class="fa fa-bank fa-lg"></i> {% trans 'Accounts' %} <span
                class="badge badge-pill badge-primary pull-right">{{counts.accounts}}</span></a>

            <div data-toggle="collapse" data-target="#transactions" class="collapsed active">
              <a href="##" class="list-group-item list-group-item-action">
                <i class="fa fa-credit-card fa-lg"></i> {% trans 'Transactions' %} <span
                  class="badge badge-pill badge-primary pull-right">{{counts.transactions_uncategorized}}</span></a>
            </div>
            <div class="sub-menu collapse" id="transactions">
              <a href="{% url 'transactions' %}" class="list-group-item list-group-item-action">
                <i class="fa fa-list fa-lg"></i> {% trans 'List' %} <span
                  class="badge badge-pill badge-primary pull-right">{{counts.transactions}}</span></a>
              <a href="{% url 'transactions_categorize' %}" class="list-group-item list-group-item-action">
                <i class="fa fa-tags fa-lg"></i> {% trans 'Categorize' %} <span
                  class="badge badge-pill badge-primary pull-right">{{counts.transactions_uncategorized}}</span></a>
            </div>

            <a href="{% url 'categories' %}" class="list-group-item list-group-item-action">
              <i class="fa fa-tags fa-lg"></i> {% trans 'Categories' %} <span
                class="badge badge-pill badge-primary pull-right">{{counts.categories}}</span></a>

            <a href="{% url 'logout' %}" class="list-group-item list-group-item-action">
              <i class="fa fa-sign-out fa-lg"></i> {% trans 'Log out' %} </a>
            {% else %}
            <a href="{% url 'login' %}" class="list-group-item list-group-item-action">
              <i class="fa fa-sign-in fa-lg"></i> {% trans 'Log in' %} </a>
            {% endif %}
          </div> <!-- menu list -->
        </div>
        {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>

  {% block scripts %}
  {% endblock %}

</body>

</html>

src/fints_downloader/templates/categories.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load humanize %}

{% block content %}
<div class="container">
    <div class="row">
        <div class=col text-center>
            <h1>{% trans 'Categories' %}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <table data-classes="table table-striped table-hover"
                    data-toggle="table"
                    data-pagination="true"
                    data-search="true"
                    data-show-pagination-switch="true"
                    data-show-search-clear-button="true"
                    data-show-toggle="true"
                    data-sortable="true">
                <thead>
                    <tr>
                        <th>{% trans 'Name' %}</th>
                        <th>{% trans 'LtD # of transactions' %}</th>
                        <th>{% trans 'LtD Sum transactions' %}</th>
                        <th>{% trans 'MtD # of transactions' %}</th>
                        <th>{% trans 'MtD Sum transactions' %}</th>
                    </tr>
                </thead>
                <tbody> 
                {% for category in categories %}
                    <tr>
                        <td><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></td>
                        <td>{{ category.count_transactions_ltd }}</td>
                        <td>{{ category.sum_transactions_ltd|floatformat:2|intcomma }}</td>
                        <td>{{ category.count_transactions_mtd }}</td>
                        <td>{{ category.sum_transactions_mtd|floatformat:2|intcomma }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

src/fints_downloader/templates/tag.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Tag View</h1>

  <p>TODO: show something</p>
{% endblock %}